# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 275);
user_pref("datareporting.sessions.current.startTime", "1514243631464");
user_pref("datareporting.sessions.current.totalTime", 1);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-pt-PT@thunderbird.mozilla.org\":{\"version\":\"52.5.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-pt-PT@thunderbird.mozilla.org.xpi\",\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"langpack-pt-BR@thunderbird.mozilla.org\":{\"version\":\"52.5.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-pt-BR@thunderbird.mozilla.org.xpi\",\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"52.5.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"runInSafeMode\":false,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7Ba62ef8ec-5fdc-40c2-873c-223b8a6925cc%7D:3.3,%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D:5.4.5,messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.5.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.5.0");
user_pref("extensions.lastPlatformVersion", "52.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-pt-PT@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-pt-PT@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"52.5.0\",\"st\":1511371212000},\"{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\":{\"d\":\"/usr/lib/thunderbird/extensions/{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\",\"e\":true,\"v\":\"3.3\",\"st\":1513958505000,\"mt\":1262304000000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.5.0\",\"st\":1511370540000},\"langpack-pt-BR@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-pt-BR@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"52.5.0\",\"st\":1511371212000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"d\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"e\":true,\"v\":\"52.5.0\",\"st\":1511371154000},\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"d\":\"/usr/lib/thunderbird/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"e\":true,\"v\":\"5.4.5\",\"st\":1513958506000,\"mt\":1262304000000},\"messagingmenu@mozilla.com\":{\"d\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"e\":true,\"v\":\"1.3.1\",\"st\":1511370483000}}}");
user_pref("mail.ui-rdf.version", 15);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("toolkit.telemetry.cachedClientID", "01df35fb-65c1-48fc-9320-6459117e1e78");
user_pref("toolkit.telemetry.previousBuildID", "20171122155701");
